name: GitHub Actions Demo

on: [push]

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo Hello World"
        run: echo "Hello, World!"

  echo_introduction:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo Introduction"
        run: echo "My name is Tanaka."