name: GitHub Actions Demo

on: [push]

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo Hello World"
        run: |
          echo "Hello, World!"
          echo "This is a demo of GitHub Actions."
          cd /no_exist_dir