name: GitHub Actions Demo

on: [push]

jobs:
  echo_hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo Hello World"
        run: echo "Hello, World!"
      - name: "Change Directory"
        run: cd /no_exist_dir